name: Publish Package

on:
  push:
    branches:
      - main

jobs:
  build_publish:
    name: Building and Publishing Package to PYPI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Get Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip3 install -r requirements.txt; fi
          python3 -m pip install --upgrade build
          python3 -m pip install --upgrade twine

      - name: Build Package
        run: |
          python3 -m build

      - name: Publish distribution 📦 to Test PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.TESTPYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
